#import "../setup/preamble.typ": template
#import "../setup/commands.typ": *
#import "../setup/ctheorems.typ": *

#show: template

#let chapter = [

= Metric Graphs
Before defining metric graphs, we first cite a standard result about the relationship between length functions and distances on graphs.
#lem[Lengths induce Distances][
  Let $G = (V,E)$ be a connected, simple graph with a length function $ell: E -> RR_+$. It induces a metric $dist_ell$ on $V$ by taking the shortest path distances, that is: 
  $ dist_ell (u,v) := min_(P "is a path"\ "from "u" to "v) quad sum_(e in P) thick ell(e) quad quad quad "for all" u,v in V $
  If further $ell$ fulfills the triangle inequality, then $dist_ell$ extends $ell$ to $V$, that is, 
  $ dist_ell (u,v) = ell(u,v) quad quad "for all" u,v in V $
]

#def[Metric Graphs][
  Let $G = (V,E)$ be a finite, connected, simple graph with a length function $ell: E -> RR_+$ fulfilling the triangle inequality. Assume that $E$ is represented as an orientation, that is, a subset of $V times V$ such that at most one of $(u,v)$ and $(v,u)$ is in $E$.

  We create a set $Gamma$ by taking a copy of the closed interval $[0, ell(e)]$ for each edge $e=(u, v) in E$ and identifying the endpoints $0$ and $ell(e)$ with the vertices $u$ and $v$ respectively. 
  
  More formally, consider the disjoint union
  $ P := union.sq.big_(e in E) [0, ell(e)] $
  where we denote the point corresponding to $e in E$ and $t in [0, ell(e)]$ by $scp(e,t)$. We then define $Gamma := (P union V) slash ~$, where $~$ is an equivalence relation generated by the rules
  $
  &scp((u,v), 0) &&thick thick ~thick thick u quad quad && ("identification of the start vertex") \
  &scp((u,v), ell(u,v)) && thick thick ~thick thick v quad quad && ("identification of the end vertex") \
  $
  for all $(u,v) in E$. By abuse of notation we often refer to the equivalence class $[scp(e,t)]_~$ simply as $scp(e,t)$. Call any element not representable as a vertex an _edge point_.

  Two elements $x,y in Gamma$ are _adjacent_ if they can be represented by points $scp(e,t), scp(e,t') in [0, ell(e)]$ on the same edge. We can define a length function on this graph via the euclidean distance
  $d_E (x, y) := |t-t'|$. Define $d$ as the shortest path distance on $Gamma$ with respect to this length function. The resulting metric space $(Gamma, d)$ is called the _metric graph_ induced by $G$ and $ell$.
]

Note that the extension of $d_E$ to $d$ does indeed give a metric: Because $G$ is connected, any two points in $Gamma$ can be joined by a path.

We can restrict ourselves to the following paths in the future:

#def[Direct Paths][
  A path $P$ in $Gamma$ is _direct_ if all points except possibly start- and end-points are vertices.
]

TODO: [Picture of a metric graph with direct and non-direct paths]

The justification is the following Lemma:
#lem[Distances in the Metric Graph][
  Let $scp(e,t), scp(e',t') in Gamma$.
  + Any path between $scp(e,t)$ and $scp(e',t')$ can be transformed into a direct path without increasing its length.

  + If $e=e'$, so $scp(e,t)$ and $scp(e',t')$ lie on the same edge, their distance is  $ d(scp(e,t), scp(e,t')) = abs(t-t') $
    A shortest path is given by the direct connection $(scp(e,t), scp(e',t'))$.

  + If $e!=e'$, so $scp(e,t)$ and $scp(e',t')$ lie on different edges, their distance is
    $
    d(scp(e,t), scp(e',t')) = min_(v "incident to" e \ 
    v' "incident to" e')
    d_E (scp(e,t),v) + dist_ell (v, v') + d_E (v', scp(e',t'))\
    $
    A shortest path is obtained by the concatenation
    $ (scp(e,t), v_*) * P  * (v'_*, scp(e',t')) $
    where $P$ is any shortest path from $v_*$ to $v'_*$ in the graph $G$ with edge lengths $ell$, and vertices $v_*,v'_*$ realize the minimum above.
]
#pf[
  + Any path between $scp(e,t)$ and $scp(e',t')$ can be transformed into a path that only uses vertices as intermediate points without increasing its length. This is because any segment of the path between two edge points can be replaced by the direct path along the edge, which is not longer since the euclidean distance fulfills the triangle inequality. Thus we only need to consider paths of the form $(scp(e,t), v_1,...,v_k, scp(e',t'))$ with $v_1,...,v_k in V$. This 
  
  +   Let $e = e' = (u,v)$ and $x = scp(e,t)$ and $y = scp(e,t')$. The path along the edge has length $|t-t'|$, so $d(x,y) <= |t-t'|$. We show the reverse inequality for any path that leaves the edge interval.
    Such a path must meet vertices in $V$ as intermediate points.
    If it leaves and re-enters through the same endpoint $a in {u,v}$, its length is at least
    $ d_E (x,a) + d_E (a,y) >= d_E (x,y) = |t-t'| $
    If it uses both endpoints, by 1. its length is at least
    $
    d_E (x,u) + dist_ell (u,v) + d_E (v,y)
    $
    or the analogous expression with $u,v$ swapped. Since we know $dist_ell (u,v) = ell(u,v)$ by the triangle-inequality assumption on $ell$, each of these has length at least $ell(u,v) >= |t-t'|$.

    Hence every path from $x$ to $y$ has length at least $|t-t'|$, and therefore $d(scp(e,t), scp(e,t')) = |t-t'|$.

  + By 2. we know that the path described is a shortest direct path, which is a shortest path by 1.
]

Note that in a metric graph, there are two notions of paths: combinatorial ones, which are sequences of adjacent vertices and edge points, and continuous ones, which are continuous maps from an interval to $Gamma$. To avoid ambiguity, we will refer to the former as _paths_ and to the latter as _curves_.

#def[Curves][
  Let $X$ be a metric space and $x,y in X$.
  + A _curve_ from $x$ to $y$ is a continuous map $gamma: [0,L] -> X$ with $gamma(0)=x$ and $gamma(L)=y$), where $L >= 0$ is the domain length.
  + If $gamma: [0,L] -> X$ is a curve from $x$ to $y$ and $gamma': [0,L'] -> X$ a curve from $y$ to $z$, their _concatenation_ is the curve $gamma' * gamma: [0,L+L'] -> X$ from $x$ to $z$ defined by
    $
    (gamma * gamma')(s) :=& gamma(s) && "for" s in [0,L] \
    (gamma * gamma')(s) :=& gamma'(s-L) && "for" s in [L, L+L']
    $
  + A curve $gamma: [0,L] -> X$ is _simple_ if it is injective on $[0,L)$ and on $(0,L]$.
  + A curve $gamma: [0,L] -> X$ is _geodesic_ if $d(gamma(s), gamma(t)) = |s-t|$ holds for all $s,t in [0,L]$.
]

Clearly, any geodesic curve is simple, not necessarily the other way around. The following theorem shows the connection between combinatorial paths and curves in metric graphs:

#thm[correspondence between direct Paths and Curves][
  There is a bijective map $Phi$ which maps direct paths $P$ in $Gamma$ to curves $Phi(P)=gamma_P$ in $Gamma$ whose restriction to edge intervals is geodesic. It fulfills the following properties:
  + $Phi$ preserves start-and endpoints and lengths
  + $Phi$ restricted to simple direct paths is a bijection to the simple curves
  + $Phi$ restricted to shortest direct paths is a bijection to the geodesics
]
#pf[
  We first define $Phi$ on a direct path with one segment: let $P=(scp(e,t), scp(e,t'))$ on one edge interval and $L=|t'-t|$. Set
  $ gamma: [0,L] -> Gamma, quad gamma(s) = scp(e, (1 - s/L) t + (s/L) t') $
  Since the coordinate on this edge interval is affine in $s$, we get
  $ d(gamma(s), gamma(r)) = |s-r| $
  for all $r,s in [0,L]$, so $gamma$ is geodesic, has the same endpoints as $P$, and has length $L(P)=L$.

  Uniqueness on one edge interval: If $eta:[0,L] -> Gamma$ is another geodesic with the same endpoints on this edge interval, write $eta(s)=scp(e,q(s))$. Then geodesicity implies
  $ |q(s)-q(r)| = d(eta(s), eta(r)) = |s-r| $
  for all $r,s$. Hence $q$ is an isometry of intervals with $q(0)=t$ and $q(L)=t'$, therefore
  $ q(s) = (1 - s/L) t + (s/L) t' $
  and $eta=gamma$.

  Now let $P=(p_0,p_1,...,p_k)$ be an arbitrary direct path. For each $i=1,...,k$, the pair $(p_(i-1),p_i)$ lies on one edge interval, so by the previous step there is a unique geodesic segment $gamma_i$ between them. Define
  $ Phi(P) := gamma_1 * ... * gamma_k $
  Then $Phi(P)$ is a curve from $p_0$ to $p_k$, geodesic on each edge piece, and
  $ L(Phi(P)) = sum_(i=1)^k L(gamma_i) = sum_(i=1)^k d(p_(i-1),p_i) = L(P) $

  The inverse map is obtained by taking a curve that is geodesic on each edge interval and recording, in order, the endpoints of maximal geodesic edge pieces; these produce a direct path. 

  For 2., if $P$ is simple, no vertex/edge-point is visited twice (except possibly the endpoint convention), so the concatenated edge-geodesics cannot self-intersect; hence $Phi(P)$ is simple. Conversely, if $Phi(P)$ is simple and $P$ had a repeated point, then $Phi(P)$ would attain that value at two distinct interior times, contradiction. Therefore $Phi$ restricts to a bijection between simple direct paths and simple curves.

  For 3., let $x,y$ be endpoints of $P$.
  If $P$ is shortest, then $L(P)=d(x,y)$. For any $0 <= a <= b <= L(P)$, put $u=gamma_P (a)$ and $v=gamma_P (b)$. Along $gamma_P$, the subcurve from $u$ to $v$ has length $b-a$, so $d(u,v) <= b-a$. If strict inequality held, replacing that subcurve by a shorter path would shorten $P$, contradiction. Thus $d(u,v)=b-a$ for all $a,b$, so $gamma_P$ is geodesic.
  Conversely, if $gamma_P$ is geodesic, then
  $ d(x,y) = d(gamma_P (0), gamma_P (L(P))) = L(P), $
  hence $P$ is shortest. So $Phi$ restricts to a bijection between shortest direct paths and geodesics.
]

This especially implies that $Gamma$ is a _geodesic_ metric space, that is, any two points can be joined by a geodesic curve. Furthermore, if $Gamma$ is induced by a tree, then the geodesic between any two points is unique.

We can generalize the notion of convexity to metric graphs by using geodesic curves:
#def[Geodesic Convexity][
  Let $X$ be a geodesic metric space and let $g: X -> RR$ be a function. Then $g$ is _geodesically (strictly) convex_ if the composition $g compose gamma: [0,L] -> RR$ is (strictly) convex for every geodesic curve $gamma: [0,L] -> X$ (where $L = d(gamma(0), gamma(L))$).
]
We call this simply _convexity_ when the context is clear.

If $Gamma$ is a tree, then $Gamma$ there always exists a unique simple (and thus geodesic) path between any two points. Hence, in this case, we can equivalently define geodesic convexity by only considering the unique simple curve instead of all geodesic curves.

]
#chapter

